name: EnderHoppers
main: com.BASeCamp.GPEnderHoppers.GPEnderHopper
depends: GriefProtection
softdepends: BetterEnderChest
version: 1.2
commands:
   claimecpull:
      description: Toggle Enderchest Pull capability in the current claim. (take items from a EnderChest)
      permission: EnderHoppers.Manipulate
   claimecpush:
      description: Toggle Enderchest Push capability in the current claim. (Put items in an EnderChest)
      permission: EnderHoppers.Manipulate
permissions:
  EmderHoppers.Manipulate:
    description: Allows players to toggle Ender Hoppers for the current claim.
    default: true